version: '3.5'
services:
  zabbix-proxy-build:
    container_name: zabbix_proxy_build
    image: nginx
    restart: always
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8120:8120"

  tj-proxy:
    container_name: tj-proxy
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8019:8019"

  portainer:
    restart: always
    container_name: portainer
    image: portainer/agent:2.19.1
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  zabbix-build-base:
    restart: always
    build:
      context: ./Dockerfiles/build-base/alpine
      cache_from:
        - alpine:3.17
    image: zabbix-build-base:alpine-local

  zabbix-build-pgsql:
    restart: always
    build:
      context: ./Dockerfiles/build-pgsql/alpine
      cache_from:
        - alpine:3.17
      args:
        BUILD_BASE_IMAGE: zabbix-build-base:alpine-local
    image: zabbix-build-pgsql:alpine-local
    depends_on:
      - zabbix-build-base

  zabbix-build-mysql:
    restart: always
    build:
      context: ./Dockerfiles/build-mysql/alpine
      cache_from:
        - alpine:3.17
      args:
        BUILD_BASE_IMAGE: zabbix-build-base:alpine-local
    image: zabbix-build-mysql:alpine-local
    profiles:
      - all
    depends_on:
      - zabbix-build-base

  zabbix-build-sqlite3:
    restart: always
      #  31,1          Top
