version: '3.5'
services:
    web-server:
        image: ngnix:stable
        container_name: myngnix
        volumes:
            -   '/opt/web/html:/var/www/html'
            -   '/opt/web/pics:/var/www/pictures'
        environment:
            - 'NGINX_HOST=web.romnero.de'
            - 'NGINX_PORT=80'
        ports:
            - '80:80'
            - '443:443'
        restart: unless-stopped
networks:
    default:
        driver: bridge
        name: web-net





#FROM ubuntu:22.04
#LABEL authors="semenov_av"
#LABEL type="Тестовый докер файл для portainer"
#RUN apt-get update
#RUN apt-get install apache2 -y
#EXPOSE 80
#CMD ["apache2ctl", "-D, "daemon off;", "FOREGROUND"]







